    name: Elixir CI
    
    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    
    jobs:
      build:
        name: Build and test
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-elixir@v1
          with:
            elixir-version: ‘1.13.1’
            otp-version: '24.0.5'
        - name: Restore dependencies cache
          uses: actions/cache@v2
          with:
            path: deps
            key: $
            restore-keys: $-mix-
        - name: Install dependencies
          run: mix deps.get
        - name: Run tests
          run: mix test